// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-MF0yrvaVxQMaFHnGK7IJ81HKnq5fn6M',
    appId: '1:1017903150282:web:f9abfe596cbdec53527033',
    messagingSenderId: '1017903150282',
    projectId: 'quickbite-b572c',
    authDomain: 'quickbite-b572c.firebaseapp.com',
    storageBucket: 'quickbite-b572c.firebasestorage.app',
    measurementId: 'G-E5SJQ5XKC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Gb5mVSRpEhpP_ln_LiGD1dNDJpT2RYE',
    appId: '1:1017903150282:android:8decd65431451ef5527033',
    messagingSenderId: '1017903150282',
    projectId: 'quickbite-b572c',
    storageBucket: 'quickbite-b572c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7YhhFLqe6pSQ3NSkp6CQhH8qAJc2q14',
    appId: '1:1017903150282:ios:b5ce527877ff8d0d527033',
    messagingSenderId: '1017903150282',
    projectId: 'quickbite-b572c',
    storageBucket: 'quickbite-b572c.firebasestorage.app',
    iosBundleId: 'com.example.quickbiteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7YhhFLqe6pSQ3NSkp6CQhH8qAJc2q14',
    appId: '1:1017903150282:ios:b5ce527877ff8d0d527033',
    messagingSenderId: '1017903150282',
    projectId: 'quickbite-b572c',
    storageBucket: 'quickbite-b572c.firebasestorage.app',
    iosBundleId: 'com.example.quickbiteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-MF0yrvaVxQMaFHnGK7IJ81HKnq5fn6M',
    appId: '1:1017903150282:web:b6ef40bd26a28620527033',
    messagingSenderId: '1017903150282',
    projectId: 'quickbite-b572c',
    authDomain: 'quickbite-b572c.firebaseapp.com',
    storageBucket: 'quickbite-b572c.firebasestorage.app',
    measurementId: 'G-9G336SLWJ4',
  );
}
